### ISSUE TITLE
windows编译模板问题，我是菜鸟 不动就问

### ISSUE THREAD

**Issue by xsbod** [selinuxG/Golin#10]
package command-line-arguments
        imports golin/cmd
        imports golin/port
        imports golin/port/crack
        imports github.com/tomatome/grdp/protocol/pdu
        imports github.com/tomatome/grdp/protocol/t125/gcc
        imports github.com/tomatome/grdp/plugin: build constraints exclude all Go files in C:\Users\Administrator\Downloads\Compressed\Golin-master\vendor\github.com\tomatome\grdp\plugin

**Comment by selinuxG** [comment]
编译的什么系统架构？

**Comment by Thinkberry** [comment]
同样遇到了这个问题
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set CC=gcc
set CXX=g++
set CGO_ENABLED=0

go version go1.21.1 windows/amd64

**Comment by selinuxG** [comment]
开启CGO

**Comment by xsbod** [comment]
用的windows

**Comment by zzti** [comment]
我的也是这个错误

**Comment by xsbod** [comment]
修改
set CGO_ENABLED=1
安装gcc MinGW-W64 GCC-8.1.0  就OJBK了

**Comment by zzti** [comment]
> 修改 set CGO_ENABLED=1 安装gcc MinGW-W64 GCC-8.1.0 就OJBK了

这样可以,谢谢

**Comment by Thinkberry** [comment]
> 修改 set CGO_ENABLED=1 安装gcc MinGW-W64 GCC-8.1.0 就OJBK了

谢谢，解决了！
