### ISSUE TITLE
只能本地127.0.0.1访问页面吗？

### ISSUE THREAD

**Issue by shellsec** [selinuxG/Golin#11]
https://127.0.0.1:1818/golin/dj
怎么改成外不可以访问，或者按模块开，开那个定级的模块

**Comment by selinuxG** [comment]
是可以对外访问的，启动web时可以指定当前主机的网卡ip，也可以任意地址，如：
golin  web -i 0.0.0.0

**Comment by shellsec** [comment]
golin web -i 0.0.0.0 您正试图导入一个与已存在证书相同颁发者和序列号但却不相同的证书。

**Comment by selinuxG** [comment]
直接访问地址打不开吗

**Comment by shellsec** [comment]
换个谷歌浏览器好了
