### ISSUE TITLE
这个怎么用了，咋运行了，不太会用哇

### ISSUE THREAD

**Issue by bi-Amazing** [selinuxG/Golin#12]

**Comment by selinuxG** [comment]
如果需要进行资产扫描（端口、协议、组件、漏洞）可以使用这个方法（cmd打开):
golin.exe port -i 192.168.1.1/24

**Comment by bi-Amazing** [comment]
> 如果需要进行资产扫描（端口、协议、组件、漏洞）可以使用这个方法（cmd打开）： golin.exe port -i 192.168.1.1/24
里面没有看到golin.exe这个文件哇

**Comment by bi-Amazing** [comment]
> 如果需要进行资产扫描（端口、协议、组件、漏洞）可以使用这个方法（cmd打开): golin.exe port -i 192.168.1.1/24

golin不是内部命令，无法执行，是得需要go的环境变量吗

**Comment by selinuxG** [comment]
你需要在程序的相同目录下打开cmd，如果是windows的话，你需要使用golin.exe来运行，加上后缀

**Comment by bi-Amazing** [comment]
> 你需要在程序的相同目录下打开cmd，如果是windows的话，你需要使用golin.exe来运行，加上后缀

Golin.exe怎么搞

**Comment by selinuxG** [comment]
https://github.com/selinuxG/Golin/releases/download/1.2.4/golin.exe
从这下载

**Comment by bi-Amazing** [comment]
> https://github.com/selinuxG/Golin/releases/download/1.2.4/golin.exe 从这下载

👍🏿👍🏿👍🏼👍🏼👍👍🏻，，okok，感谢老哥🤙🤙🤙

**Comment by selinuxG** [comment]
好滴，有bug或者需求都可以提，好用的话欢迎给star😊

**Comment by pearpro1** [comment]
不行，这个golin.exe 文件都没了，go语言的环境配置老是有问题
能不能出一篇怎么使用golin啊

**Comment by selinuxG** [comment]
亲，咋在已关闭的issues中提问题，很容易看不到这个消息的，最新版要从[https://github.com/selinuxG/Golin/releases/](https://github.com/selinuxG/Golin/releases/download/1.2.4/golin.exe)这里下载，这个地址是不变的，带版本的地址是会变的

**Comment by q1906155009** [comment]
不会用
