### ISSUE TITLE
WEB,单主机采集，显示错误

### ISSUE THREAD

**Issue by bi-Amazing** [selinuxG/Golin#13]

**Comment by selinuxG** [comment]
给个操作步骤，以及截图。

**Comment by bi-Amazing** [comment]
> 给个操作步骤，以及截图。


<img width="954" alt="Snipaste_2023-09-26_11-06-56" src="https://github.com/selinuxG/Golin/assets/112627314/ad8332b9-defe-4bcf-84c2-229505abcbd6">
填了IP地址，账号，密码，端口，提交后提示错误

**Comment by selinuxG** [comment]
你方便加我个微信定位下问题吗？SelinuxG

**Comment by bi-Amazing** [comment]
> 你方便加我个微信定位下问题吗？SelinuxG

好的，加你了amazing

**Comment by selinuxG** [comment]
问题已定位修复，已更新。
