### ISSUE TITLE
web页面，单主机采集模式，panic：runtime error

### ISSUE THREAD

**Issue by 2637011902** [selinuxG/Golin#14]
您好，我在运行程序时出现了下面这样的报错
我在web页面提交的信息如下
![image](https://github.com/selinuxG/Golin/assets/67538732/e585ac21-a058-4eda-9fa7-dcc92ec175f8)
提交之后程序就停止运行了，就出现了下面的报错
![image](https://github.com/selinuxG/Golin/assets/67538732/105b2dc4-e46a-4bf8-95a3-502d266fbe91)
请问一下是哪里出现了问题呢

**Comment by selinuxG** [comment]
目标主机是什么操作系统，具备/etc/passwd，/etc/shadow文件以及chage命令吗？

**Comment by 2637011902** [comment]
centos7，两个文件都具备，chage，ss命令都具备

**Comment by selinuxG** [comment]
在目标服务器手动执行一下，截图看我看看
ss -tulnp|grep -v "Netid"
chage -l  root

**Comment by 2637011902** [comment]
![image](https://github.com/selinuxG/Golin/assets/67538732/56bbb450-36e1-45e3-8585-43731666e9a6)
![image](https://github.com/selinuxG/Golin/assets/67538732/fd60602f-8930-431b-bf2c-cc5943acdab3)

**Comment by selinuxG** [comment]
这个:是中文冒号还是英文冒号？

**Comment by 2637011902** [comment]
是英文冒号

**Comment by 2637011902** [comment]
应该是中文冒号

**Comment by selinuxG** [comment]
嗯，看着像是中文冒号，现在是按照英文冒号分隔的，如果是中文操作系统应该是中文冒号会出现这个问题，我今天会优化下这个问题发布新版本，如果着急可以可以加我微信SelinuxG，单独先发你一个优化后的。

**Comment by 2637011902** [comment]
好的，谢谢您！
