### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by L1L1L1C** [selinuxG/Golin#15]
咋安装使用啊，mac能用吗，虚拟机里报错
<img width="1011" alt="image" src="https://github.com/selinuxG/Golin/assets/110832755/e26c001e-d019-4c3f-b1a2-2e88c097aec1">

**Comment by L1L1L1C** [comment]
mac能用吗

**Comment by L1L1L1C** [comment]
师傅麻烦出一个下载安装使用教程

**Comment by L1L1L1C** [comment]
<img width="1103" alt="image" src="https://github.com/selinuxG/Golin/assets/110832755/8fe69a32-e9bd-4c79-9384-a4d679ffdbda">

**Comment by selinuxG** [comment]
你下载下来的文件大小与仓库的文件大小一致吗？

**Comment by selinuxG** [comment]
我晚点编译一个mac版本的程序提供给你。

**Comment by L1L1L1C** [comment]
> 你下载下来的文件大小与仓库的文件大小一致吗？
是一样的

**Comment by L1L1L1C** [comment]
> 我晚点编译了一个 mac 版本的程序提供给你。

感谢

**Comment by L1L1L1C** [comment]
> 我晚点编译了一个 mac 版本的程序提供给你。



> 你下载下来的文件大小与仓库的文件大小一致吗？

我的是在mac里虚拟机运行的，我用别人的电脑可以直接运行exe

**Comment by selinuxG** [comment]
Mac下的执行文件，可自行通过 upx 压缩大小（不过可能会触发 Mac 下的Gatekeeper等安全机制，导致无法直接运行。）

[golin.zip](https://github.com/selinuxG/Golin/files/12726134/golin.zip)

**Comment by L1L1L1C** [comment]
> Mac下的执行文件，可自行通过 upx 压缩大小（不过可能会触发 Mac 下的Gatekeeper等安全机制，导致无法直接运行。）
> 
> [golin.zip](https://github.com/selinuxG/Golin/files/12726134/golin.zip)

感谢大佬
