### ISSUE TITLE
自定义命令

### ISSUE THREAD

**Issue by yuanyuanbb** [selinuxG/Golin#16]
等保配置核查的命令如何进行自定义，想添加查看/etc/login.defs和/etc/pam.d/system-auth两个文件

**Comment by selinuxG** [comment]
早上好，/etc/login.defs内容的信息是有的，展示在以下位置，/etc/pam.d/system-auth我今天会继承进去，晚点可以尝试更新。
![image](https://github.com/selinuxG/Golin/assets/34471076/f1393164-41fe-4b06-85e1-40437e7b1c10)

**Comment by yuanyuanbb** [comment]
> 早上好，/etc/login.defs内容的信息是有的，展示在以下位置，/etc/pam.d/system-auth我今天会继承进去，晚点可以尝试更新。 ![image](https://user-images.githubusercontent.com/34471076/270827237-f1393164-41fe-4b06-85e1-40437e7b1c10.png)

好的，谢谢，请问下后续是否会推出针对windows系统的等保配置核查呢？

**Comment by selinuxG** [comment]
Windows现在就有，不能通过web运行，需要在cmd运行
golin.exe windows

**Comment by yuanyuanbb** [comment]
> Windows现在就有，不能通过web运行，需要在cmd运行 golin.exe windows

这么说只能测试本机？

**Comment by yuanyuanbb** [comment]
> Windows本身就不具备可以通过远程执行命令的方法

那我明白了，还是需要通过脚本的方式进行

**Comment by selinuxG** [comment]
对的，Windows操作系统只能通过本机方法运行生成报告。

**Comment by selinuxG** [comment]
/etc/pam.d/system-auth以添加到内置中，可通过golin update或手动下载更新。
