### ISSUE TITLE
没有golin文件，无法启动服务？

### ISSUE THREAD

**Issue by b2522** [selinuxG/Golin#17]
没有golin文件，无法启动服务？

**Comment by selinuxG** [comment]
你是Windows操作系统吗，需要golin.exe 启动

**Comment by b2522** [comment]
是windows，压缩包里没有golin.exe

**Comment by selinuxG** [comment]
从这下载
https://github.com/selinuxG/Golin/releases/tag/1.2.4

**Comment by b2522** [comment]
收到，谢谢！
