### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by blodrag5281** [selinuxG/Golin#19]
打包成exe为什么比你的文件大了好几倍，linux单机核查也会出现错误。

WARN    run/share.go:141    错误！不是正确的IP地址,退出！

**Comment by blodrag5281** [comment]
web方式

**Comment by blodrag5281** [comment]
./main.exe web
127.0.0.1  root   *****   22

**Comment by selinuxG** [comment]
Web下选择的什么模式，名称写的是什么

**Comment by blodrag5281** [comment]
{"level":"WARN","time":"2023-10-16 17:34:54","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}

**Comment by blodrag5281** [comment]
名称写了相同的ip地址

**Comment by selinuxG** [comment]
填写内容后，web截个图吧

**Comment by blodrag5281** [comment]
![image](https://github.com/selinuxG/Golin/assets/132682889/7ef76ece-8445-46ac-90e1-1e3c8be70ca5)

**Comment by blodrag5281** [comment]
{"level":"WARN","time":"2023-10-16 16:31:26","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}
{"level":"WARN","time":"2023-10-16 16:32:14","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}
{"level":"WARN","time":"2023-10-16 16:48:29","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}
{"level":"WARN","time":"2023-10-16 17:34:54","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}
{"level":"WARN","time":"2023-10-16 17:46:17","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}
{"level":"WARN","time":"2023-10-16 17:47:45","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}
{"level":"WARN","time":"2023-10-16 17:48:00","caller":"run/share.go:141","msg":"错误！不是正确的IP地址,退出！"}

**Comment by selinuxG** [comment]
方便的话加我个微信:SelinuxG，方便排查下问题

**Comment by selinuxG** [comment]
用户虚拟机问题，程序本身无问题，此问题已解决。
