### ISSUE TITLE
如何启动

### ISSUE THREAD

**Issue by XleeJE** [selinuxG/Golin#21]
下载下来后，怎样运行呀

**Comment by selinuxG** [comment]
你要实现啥功能？

**Comment by yutianming123** [comment]
怎么配合等保的工具使用，出个操作说明吧，啥步骤都没有

**Comment by selinuxG** [comment]
> 



> 怎么配合等保的工具使用，出个操作说明吧，啥步骤都没有

readme中不是写了吗？
golin web (通过web方式启动,仅支持等保功能)
用cmd打开程序所在目录运行，剩下的就是输入账号密码，选择模式。

**Comment by yutianming123** [comment]
ok
