### ISSUE TITLE
关于使用golin

### ISSUE THREAD

**Issue by pearpro1** [selinuxG/Golin#22]
这个项目也没有关于golin.exe 的

**Comment by selinuxG** [comment]
https://github.com/selinuxG/Golin/releases/download/1.2.5/golin.exe
这是最新的下载地址，但是这个地址在更新版本后可能会生效，https://github.com/selinuxG/Golin/releases/这个地址是不会变的。

**Comment by pearpro1** [comment]
好的，太谢谢您了

**Comment by pearpro1** [comment]
找了半天没找到

**Comment by selinuxG** [comment]
不客气，应该的。
