### ISSUE TITLE
如何调用fofa，提示环境变量未配置。如何配置呢！

### ISSUE THREAD

**Issue by jjjjpeng** [selinuxG/Golin#24]
![image](https://github.com/selinuxG/Golin/assets/37970503/e5805eb4-a1aa-4657-a6d8-05350f3ed8ac)
如图 ~后期是否可以加入检测测绘资产

**Comment by selinuxG** [comment]
在环境变量中设置fofa_email、fofa_key、fofa_size，分别对应为邮箱，key，调用api的数量

**Comment by jjjjpeng** [comment]
> 在环境变量中设置fofa_email、fofa_key、fofa_size，分别对应为邮箱，key，调用api的数量

是系统环境变量吗 还是用户的环境变量。 fofa_size指的是下载的那个次数F点吗 新手有的不太明白，感谢指点迷津

**Comment by selinuxG** [comment]
用户的就行，size就是返回的数据条数

**Comment by jjjjpeng** [comment]
> 用户的就行，size就是返回的数据条数

提示我请求fofa失败 大佬方便代码例子发一下吗 比如我 golin port --fofa（我变量配置了）+资产类型吗 比如 title=“360浏览器”
![image](https://github.com/selinuxG/Golin/assets/37970503/eac35c3d-8046-4f80-8e2a-f36a487cf445)

**Comment by selinuxG** [comment]
--fofa 'title="360浏览器"'
