### ISSUE TITLE
怎么在windows上运行这个项目

### ISSUE THREAD

**Issue by h1768101** [selinuxG/Golin#30]
package golin
	imports golin/cmd
	imports golin/port
	imports golin/port/crack
	imports github.com/tomatome/grdp/protocol/pdu
	imports github.com/tomatome/grdp/protocol/t125/gcc
	imports github.com/tomatome/grdp/plugin: build constraints exclude all Go files in C:\Users\huang\go\pkg\mod\github.com\tomatome\grdp@v0.1.0\plugin
	
	go build后，报错

**Comment by aoeeeeeee** [comment]
一样的错误

**Comment by h1768101** [comment]
> 一样的错误

解决了吗

**Comment by selinuxG** [comment]
开cgo

**Comment by h1768101** [comment]
> 开cgo

![QQ截图20240129212228](https://github.com/selinuxG/Golin/assets/60518744/18dcc1d4-baee-49ee-aeae-f73202b43d49)
我开cgo后之前的报错消失了，但是现在在goland一点运行，然后就停止了，没有web页面
