### ISSUE TITLE
多主机查询Windows组件的信息

### ISSUE THREAD

**Issue by EveHau** [selinuxG/Golin#44]
请问这个软件有多主机查询机器组件的功能吗或者提供IP 范围查询机器组件信息吗？ golin windows  只查本机Windows.html. 
golin windows 192.168.0.1-254 也只导出本机Windows.html. 

d多主机查询- 我upload 文件， 运行出错

**Comment by selinuxG** [comment]
windows安全配置核查仅允许本地运行， 不支持远程

**Comment by EveHau** [comment]
谢谢你&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SelinuxG ***@***.***&gt;
发送时间: 2024年11月8日 11:42
收件人: selinuxG/Golin ***@***.***&gt;
抄送: EveHau ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [selinuxG/Golin] 多主机查询Windows组件的信息 (Issue #44)





 
windows安全配置核查仅允许本地运行， 不支持远程
