### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by MuMuloveU** [selinuxG/Golin#5]
编译时报错
package command-line-arguments
        imports golin/cmd
        imports golin/port
        imports golin/port/crack
        imports github.com/tomatome/grdp/protocol/pdu
        imports github.com/tomatome/grdp/protocol/t125/gcc
        imports github.com/tomatome/grdp/plugin: build constraints exclude all Go files in C:\Users\anhunsec\go\pkg\mod\github.com\tomatome\grdp@v0.1.0\plugin
        
疑似mod文件有误，但是我不懂go语言开发，以下是AI的分析

根据错误信息看,在导入github.com/tomatome/grdp/plugin模块时,出现了编译错误。

这是因为build constraints exclude all Go files in C:\Users\anhunsec\go\pkg\mod\github.com\tomatome\grdp@v0.1.0\plugin导致该模块下的所有Go源文件被排除在编译构建之外。

要解决这个问题,可以检查一下构建脚本或配置,找到哪里设置了这个exclude约束,然后将其删除或调整,确保不会排除实际需要编译的代码。

常见的解决办法包括:

    删除导致exclude的构建标签或注释,如// +build ignore
    调整构建配置,不要全局exclude该模块下的代码
    如果只需要排除部分文件,可以用更精细的正则表达式,不要全部排除
    在导入语句中使用替换路径,避开被exclude的代码
    将依赖的代码移到另一个模块中,不受exclude影响
    提交issue给项目作者,说明exclude造成的问题

总之,需要定位导致exclude的原因,然后调整构建配置或源码,让真正需要的代码部分不被错误排除在编译构建之外。

如果还有疑问,可以提供更多编译错误输出和项目代码信息,我来帮您进一步分析。

**Comment by selinuxG** [comment]
grdp库的问题，需要开启cgo编译
SET CGO_ENABLED=0
