### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shihuajushi12** [selinuxG/Golin#8]
![Screen Capture_select-area_20230918113712](https://github.com/selinuxG/Golin/assets/9305738/eedbef39-cc1f-4055-81e0-1a9f1fc7e3d3)
 兄弟，报错了，哈哈

**Comment by selinuxG** [comment]
又是grdp的问题，这个问题应该是偶然出现，可以先通过 -e 3389跳过扫描这个端口，或者--nocrack跳过扫描弱口令解决一下

**Comment by selinuxG** [comment]
太奇怪了，在我这从没出现这个问题，我发现在其他人电脑上会偶然出现 :(

**Comment by selinuxG** [comment]
此问题应该是出现在高并发情况下会偶然
出现，后续我减少下rdp模式的默认字典

**Comment by selinuxG** [comment]
hello，可以下载一下最新版，已经根据特定情况处理优化了，看看还会出现此情况吗？
