### ISSUE TITLE
linux合规性检查报错

### ISSUE THREAD

**Issue by lichen0730** [selinuxG/Golin#9]
![image](https://github.com/selinuxG/Golin/assets/42528581/80ca8c18-d939-4f69-8481-e47cc3ee672e)
想单主机采集，报错了

**Comment by selinuxG** [comment]
怎么操作出现的，密码是包含～符号吗？

**Comment by lichen0730** [comment]
> 怎么操作出现的，密码是包含～符号吗？
就是常规的操作，账户是root，密码是小写字母加数字，不带特殊字符的

**Comment by selinuxG** [comment]
运行任意模式主机都会出现此问题吗？

**Comment by selinuxG** [comment]
用的账户是不是不是管理用户，或者有没有chage这个命令？

**Comment by 1554073781** [comment]
![图片](https://github.com/selinuxG/Golin/assets/72782324/f247032b-77fa-4940-b428-fe41bc9364df)
用root账号报错

**Comment by selinuxG** [comment]
可以更新下版本，再试试。

**Comment by selinuxG** [comment]
新版本已修复。
